/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    messages: Message;
    media: Media;
    users: User;
    'totp-attempts': TotpAttempt;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'totp-attempts': TotpAttemptsSelect<false> | TotpAttemptsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'nl' | 'de' | 'fr') | ('en' | 'nl' | 'de' | 'fr')[];
  globals: {
    'site-site': SiteSite;
    'site-home': SiteHome;
    'site-seo': SiteSeo;
    'site-hero': SiteHero;
    'site-problem': SiteProblem;
    'site-steps': SiteStep;
    'site-apps': SiteApp;
    'site-status': SiteStatus;
    'site-today': SiteToday;
    'site-about': SiteAbout;
    'site-contact': SiteContact;
    'site-aud-municipalities': SiteAudMunicipality;
    'site-aud-fleets': SiteAudFleet;
    'site-aud-manufacturers': SiteAudManufacturer;
    'site-aud-platforms': SiteAudPlatform;
    'site-aud-investors': SiteAudInvestor;
    privacy: Privacy;
    photos: Photo;
  };
  globalsSelect: {
    'site-site': SiteSiteSelect<false> | SiteSiteSelect<true>;
    'site-home': SiteHomeSelect<false> | SiteHomeSelect<true>;
    'site-seo': SiteSeoSelect<false> | SiteSeoSelect<true>;
    'site-hero': SiteHeroSelect<false> | SiteHeroSelect<true>;
    'site-problem': SiteProblemSelect<false> | SiteProblemSelect<true>;
    'site-steps': SiteStepsSelect<false> | SiteStepsSelect<true>;
    'site-apps': SiteAppsSelect<false> | SiteAppsSelect<true>;
    'site-status': SiteStatusSelect<false> | SiteStatusSelect<true>;
    'site-today': SiteTodaySelect<false> | SiteTodaySelect<true>;
    'site-about': SiteAboutSelect<false> | SiteAboutSelect<true>;
    'site-contact': SiteContactSelect<false> | SiteContactSelect<true>;
    'site-aud-municipalities': SiteAudMunicipalitiesSelect<false> | SiteAudMunicipalitiesSelect<true>;
    'site-aud-fleets': SiteAudFleetsSelect<false> | SiteAudFleetsSelect<true>;
    'site-aud-manufacturers': SiteAudManufacturersSelect<false> | SiteAudManufacturersSelect<true>;
    'site-aud-platforms': SiteAudPlatformsSelect<false> | SiteAudPlatformsSelect<true>;
    'site-aud-investors': SiteAudInvestorsSelect<false> | SiteAudInvestorsSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
  };
  locale: 'en' | 'nl' | 'de' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * New pages for the website. A published page appears at /<language>/<address>. Fill in a language only if the page exists in that language.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Lowercase letters, digits and single dashes, for example about-us. The page appears at /<language>/<address>.
   */
  slug: string;
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  showInFooter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages sent through the contact form of the website. Delete them on request or after the retention period in the privacy statement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  handled?: boolean | null;
  receivedAt: string;
  name: string;
  email: string;
  organisation?: string | null;
  role?: string | null;
  message: string;
  language?: string | null;
  source?: string | null;
  note?: string | null;
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'site';
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "totp-attempts".
 */
export interface TotpAttempt {
  id: string;
  attempts: number;
  lockUntil?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  showInFooter?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  handled?: T;
  receivedAt?: T;
  name?: T;
  email?: T;
  organisation?: T;
  role?: T;
  message?: T;
  language?: T;
  source?: T;
  note?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "totp-attempts_select".
 */
export interface TotpAttemptsSelect<T extends boolean = true> {
  id?: T;
  attempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-site".
 */
export interface SiteSite {
  id: number;
  site_name?: string | null;
  meta_description?: string | null;
  company_line?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-home".
 */
export interface SiteHome {
  id: number;
  home_problem_line?: string | null;
  status_short?: string | null;
  cta_title?: string | null;
  cta_text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-seo".
 */
export interface SiteSeo {
  id: number;
  seo_home?: string | null;
  seo_problem?: string | null;
  seo_how?: string | null;
  seo_apps?: string | null;
  seo_contact?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-hero".
 */
export interface SiteHero {
  id: number;
  hero_eyebrow?: string | null;
  hero_title?: string | null;
  hero_text?: string | null;
  hero_cta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-problem".
 */
export interface SiteProblem {
  id: number;
  problem_title?: string | null;
  problem_text?: string | null;
  fact1_value?: string | null;
  fact1_label?: string | null;
  fact1_source?: string | null;
  fact1_url?: string | null;
  fact2_value?: string | null;
  fact2_label?: string | null;
  fact2_source?: string | null;
  fact2_url?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-steps".
 */
export interface SiteStep {
  id: number;
  steps_title?: string | null;
  step1_title?: string | null;
  step1_text?: string | null;
  step2_title?: string | null;
  step2_text?: string | null;
  step3_title?: string | null;
  step3_text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-apps".
 */
export interface SiteApp {
  id: number;
  apps_title?: string | null;
  app1_title?: string | null;
  app1_text?: string | null;
  app2_title?: string | null;
  app2_text?: string | null;
  app3_title?: string | null;
  app3_text?: string | null;
  app4_title?: string | null;
  app4_text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status".
 */
export interface SiteStatus {
  id: number;
  status_title?: string | null;
  status_text?: string | null;
  status_note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-today".
 */
export interface SiteToday {
  id: number;
  today_enabled?: string | null;
  seo_today?: string | null;
  today_title?: string | null;
  today_lead?: string | null;
  today_exists_title?: string | null;
  today_item1?: string | null;
  today_item2?: string | null;
  today_item3?: string | null;
  today_gap_title?: string | null;
  today_gap_text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-about".
 */
export interface SiteAbout {
  id: number;
  about_title?: string | null;
  about_text?: string | null;
  p1_name?: string | null;
  p1_role?: string | null;
  p1_bio?: string | null;
  p1_link?: string | null;
  p2_name?: string | null;
  p2_role?: string | null;
  p2_bio?: string | null;
  p2_link?: string | null;
  company_details?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contact".
 */
export interface SiteContact {
  id: number;
  contact_title?: string | null;
  contact_text?: string | null;
  contact_reply?: string | null;
  linkedin_url?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-municipalities".
 */
export interface SiteAudMunicipality {
  id: number;
  aud_municipalities_seo?: string | null;
  aud_municipalities_title?: string | null;
  aud_municipalities_lead?: string | null;
  aud_municipalities_p1?: string | null;
  aud_municipalities_p2?: string | null;
  aud_municipalities_p3?: string | null;
  aud_municipalities_q1?: string | null;
  aud_municipalities_a1?: string | null;
  aud_municipalities_q2?: string | null;
  aud_municipalities_a2?: string | null;
  aud_municipalities_q3?: string | null;
  aud_municipalities_a3?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-fleets".
 */
export interface SiteAudFleet {
  id: number;
  aud_fleets_seo?: string | null;
  aud_fleets_title?: string | null;
  aud_fleets_lead?: string | null;
  aud_fleets_p1?: string | null;
  aud_fleets_p2?: string | null;
  aud_fleets_p3?: string | null;
  aud_fleets_q1?: string | null;
  aud_fleets_a1?: string | null;
  aud_fleets_q2?: string | null;
  aud_fleets_a2?: string | null;
  aud_fleets_q3?: string | null;
  aud_fleets_a3?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-manufacturers".
 */
export interface SiteAudManufacturer {
  id: number;
  aud_manufacturers_seo?: string | null;
  aud_manufacturers_title?: string | null;
  aud_manufacturers_lead?: string | null;
  aud_manufacturers_p1?: string | null;
  aud_manufacturers_p2?: string | null;
  aud_manufacturers_p3?: string | null;
  aud_manufacturers_q1?: string | null;
  aud_manufacturers_a1?: string | null;
  aud_manufacturers_q2?: string | null;
  aud_manufacturers_a2?: string | null;
  aud_manufacturers_q3?: string | null;
  aud_manufacturers_a3?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-platforms".
 */
export interface SiteAudPlatform {
  id: number;
  aud_platforms_seo?: string | null;
  aud_platforms_title?: string | null;
  aud_platforms_lead?: string | null;
  aud_platforms_p1?: string | null;
  aud_platforms_p2?: string | null;
  aud_platforms_p3?: string | null;
  aud_platforms_q1?: string | null;
  aud_platforms_a1?: string | null;
  aud_platforms_q2?: string | null;
  aud_platforms_a2?: string | null;
  aud_platforms_q3?: string | null;
  aud_platforms_a3?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Switch the language at the top of the page. A required text left empty falls back to the default text of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-investors".
 */
export interface SiteAudInvestor {
  id: number;
  aud_investors_seo?: string | null;
  aud_investors_title?: string | null;
  aud_investors_lead?: string | null;
  aud_investors_p1?: string | null;
  aud_investors_p2?: string | null;
  aud_investors_p3?: string | null;
  aud_investors_q1?: string | null;
  aud_investors_a1?: string | null;
  aud_investors_q2?: string | null;
  aud_investors_a2?: string | null;
  aud_investors_q3?: string | null;
  aud_investors_a3?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Blank line = new paragraph. A line starting with "# " is a heading. Have this text checked by a lawyer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Photos of the website. Upload real photos only. The sharing image is shown when the site is shared (1200 x 630).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  hero?: (number | null) | Media;
  problem?: (number | null) | Media;
  status?: (number | null) | Media;
  social?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-site_select".
 */
export interface SiteSiteSelect<T extends boolean = true> {
  site_name?: T;
  meta_description?: T;
  company_line?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-home_select".
 */
export interface SiteHomeSelect<T extends boolean = true> {
  home_problem_line?: T;
  status_short?: T;
  cta_title?: T;
  cta_text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-seo_select".
 */
export interface SiteSeoSelect<T extends boolean = true> {
  seo_home?: T;
  seo_problem?: T;
  seo_how?: T;
  seo_apps?: T;
  seo_contact?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-hero_select".
 */
export interface SiteHeroSelect<T extends boolean = true> {
  hero_eyebrow?: T;
  hero_title?: T;
  hero_text?: T;
  hero_cta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-problem_select".
 */
export interface SiteProblemSelect<T extends boolean = true> {
  problem_title?: T;
  problem_text?: T;
  fact1_value?: T;
  fact1_label?: T;
  fact1_source?: T;
  fact1_url?: T;
  fact2_value?: T;
  fact2_label?: T;
  fact2_source?: T;
  fact2_url?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-steps_select".
 */
export interface SiteStepsSelect<T extends boolean = true> {
  steps_title?: T;
  step1_title?: T;
  step1_text?: T;
  step2_title?: T;
  step2_text?: T;
  step3_title?: T;
  step3_text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-apps_select".
 */
export interface SiteAppsSelect<T extends boolean = true> {
  apps_title?: T;
  app1_title?: T;
  app1_text?: T;
  app2_title?: T;
  app2_text?: T;
  app3_title?: T;
  app3_text?: T;
  app4_title?: T;
  app4_text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status_select".
 */
export interface SiteStatusSelect<T extends boolean = true> {
  status_title?: T;
  status_text?: T;
  status_note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-today_select".
 */
export interface SiteTodaySelect<T extends boolean = true> {
  today_enabled?: T;
  seo_today?: T;
  today_title?: T;
  today_lead?: T;
  today_exists_title?: T;
  today_item1?: T;
  today_item2?: T;
  today_item3?: T;
  today_gap_title?: T;
  today_gap_text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-about_select".
 */
export interface SiteAboutSelect<T extends boolean = true> {
  about_title?: T;
  about_text?: T;
  p1_name?: T;
  p1_role?: T;
  p1_bio?: T;
  p1_link?: T;
  p2_name?: T;
  p2_role?: T;
  p2_bio?: T;
  p2_link?: T;
  company_details?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contact_select".
 */
export interface SiteContactSelect<T extends boolean = true> {
  contact_title?: T;
  contact_text?: T;
  contact_reply?: T;
  linkedin_url?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-municipalities_select".
 */
export interface SiteAudMunicipalitiesSelect<T extends boolean = true> {
  aud_municipalities_seo?: T;
  aud_municipalities_title?: T;
  aud_municipalities_lead?: T;
  aud_municipalities_p1?: T;
  aud_municipalities_p2?: T;
  aud_municipalities_p3?: T;
  aud_municipalities_q1?: T;
  aud_municipalities_a1?: T;
  aud_municipalities_q2?: T;
  aud_municipalities_a2?: T;
  aud_municipalities_q3?: T;
  aud_municipalities_a3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-fleets_select".
 */
export interface SiteAudFleetsSelect<T extends boolean = true> {
  aud_fleets_seo?: T;
  aud_fleets_title?: T;
  aud_fleets_lead?: T;
  aud_fleets_p1?: T;
  aud_fleets_p2?: T;
  aud_fleets_p3?: T;
  aud_fleets_q1?: T;
  aud_fleets_a1?: T;
  aud_fleets_q2?: T;
  aud_fleets_a2?: T;
  aud_fleets_q3?: T;
  aud_fleets_a3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-manufacturers_select".
 */
export interface SiteAudManufacturersSelect<T extends boolean = true> {
  aud_manufacturers_seo?: T;
  aud_manufacturers_title?: T;
  aud_manufacturers_lead?: T;
  aud_manufacturers_p1?: T;
  aud_manufacturers_p2?: T;
  aud_manufacturers_p3?: T;
  aud_manufacturers_q1?: T;
  aud_manufacturers_a1?: T;
  aud_manufacturers_q2?: T;
  aud_manufacturers_a2?: T;
  aud_manufacturers_q3?: T;
  aud_manufacturers_a3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-platforms_select".
 */
export interface SiteAudPlatformsSelect<T extends boolean = true> {
  aud_platforms_seo?: T;
  aud_platforms_title?: T;
  aud_platforms_lead?: T;
  aud_platforms_p1?: T;
  aud_platforms_p2?: T;
  aud_platforms_p3?: T;
  aud_platforms_q1?: T;
  aud_platforms_a1?: T;
  aud_platforms_q2?: T;
  aud_platforms_a2?: T;
  aud_platforms_q3?: T;
  aud_platforms_a3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-aud-investors_select".
 */
export interface SiteAudInvestorsSelect<T extends boolean = true> {
  aud_investors_seo?: T;
  aud_investors_title?: T;
  aud_investors_lead?: T;
  aud_investors_p1?: T;
  aud_investors_p2?: T;
  aud_investors_p3?: T;
  aud_investors_q1?: T;
  aud_investors_a1?: T;
  aud_investors_q2?: T;
  aud_investors_a2?: T;
  aud_investors_q3?: T;
  aud_investors_a3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  hero?: T;
  problem?: T;
  status?: T;
  social?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}