'use strict';
/** People, audit log, security overview. */
const { esc, asset } = require('../../views');
const { qrSvg } = require('../../qr');
const media = require('../media');
const { avatar, icon, nf, relTime, shell, table, when } = require('./common');

const ROLE_INFO = { beheerder: ['Beheerder', 'Alles, ook gebruikers, instellingen en auditlog.'], editor: ['Editor', 'Teksten, pagina’s, media en berichten; mag publiceren en voorstellen beoordelen.'], redacteur: ['Redacteur', 'Schrijft en bewaart concepten; dient wijzigingen in ter beoordeling, publiceert niet zelf.'], lezer: ['Lezer', 'Alleen kijken, niets wijzigen.'] };
function usersPage(ctx, { list, sessions = {}, flash, link = null }) {
	const me = ctx.session.user;
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const roleSel = (value, id, disabled) => `<select id="${id}" name="rol"${disabled ? ' disabled' : ''}>${Object.keys(ROLE_INFO).map((r) => `<option value="${r}"${value === r ? ' selected' : ''}>${esc(ROLE_INFO[r][0])}</option>`).join('')}</select>`;
	const legend = `<div class="rolecards">${Object.entries(ROLE_INFO).map(([r, [l, d]]) => `<div class="card mini"><strong>${esc(l)}</strong><span class="meta">${esc(d)}</span><span class="meta">${list.filter((u) => u.rol === r && u.actief).length} actief</span></div>`).join('')}</div>`;
	const card = (u) => {
		const self = u.id === me.id;
		const n = sessions[u.id] || 0;
		return `<article class="card ucard${u.actief ? '' : ' off'}">
<div class="u-head">${avatar(u.naam, 'lg')}<div class="u-id"><strong>${esc(u.naam)}${self ? ' <span class="pill st-standaard">Jij</span>' : ''}</strong><span class="meta">${esc(u.email)}</span></div>
<div class="u-tags"><span class="pill st-role">${esc(ROLE_INFO[u.rol][0])}</span>${u.tweestaps ? '<span class="pill ok">2FA aan</span>' : '<span class="pill st-warn">Geen 2FA</span>'}${u.actief ? '' : '<span class="pill st-leeg">Uitgeschakeld</span>'}</div></div>
<p class="meta u-meta">Laatste login: ${u.laatste_login ? esc(relTime(u.laatste_login)) : 'nog nooit'} · ${n} actieve sessie${n === 1 ? '' : 's'}</p>
<details class="manage"><summary class="btn-link secondary small">Beheren</summary><div class="manage-grid">
<form method="post" action="/admin/gebruikers/${u.id}" class="mbox">${csrf}<h3>Gegevens</h3><div class="row"><label for="n${u.id}">Naam</label><input id="n${u.id}" name="naam" value="${esc(u.naam)}" maxlength="80" required></div><div class="row"><label for="r${u.id}">Rol</label>${roleSel(u.rol, `r${u.id}`, self)}${self ? '<p class="fhint">Je kunt je eigen rol niet wijzigen.</p>' : ''}</div>
${self ? '<input type="hidden" name="actief" value="1">' : `<label class="chk"><input type="checkbox" name="actief" value="1"${u.actief ? ' checked' : ''}> Account actief</label>`}<button class="small" type="submit">Opslaan</button></form>
<form method="post" action="/admin/gebruikers/${u.id}/wachtwoord" class="mbox">${csrf}<h3>Wachtwoord</h3><div class="row"><label for="w${u.id}">Nieuw wachtwoord</label><input id="w${u.id}" name="nieuw" type="password" minlength="12" autocomplete="new-password" required><p class="fhint">Minstens 12 tekens. Alle sessies van deze gebruiker worden uitgelogd.</p></div><div class="row"><label for="h${u.id}">Jouw wachtwoord ter bevestiging</label><input id="h${u.id}" name="huidig" type="password" autocomplete="current-password" required></div><button class="small" type="submit">Wachtwoord instellen</button></form>
<div class="mbox"><h3>Beveiliging</h3>${u.tweestaps ? `<form method="post" action="/admin/gebruikers/${u.id}/2fa-uit" data-confirm="Tweestapsverificatie voor deze gebruiker uitzetten?">${csrf}<div class="row"><label for="t${u.id}">Jouw wachtwoord ter bevestiging</label><input id="t${u.id}" name="huidig" type="password" autocomplete="current-password" required></div><button class="small danger" type="submit">2FA uitzetten</button></form>` : '<p class="hint">Deze gebruiker heeft geen tweestapsverificatie. Dat kan alleen de gebruiker zelf aanzetten onder Mijn account.</p>'}
${u.actief ? `<form method="post" action="/admin/gebruikers/${u.id}/herstellink" class="mt">${csrf}<div class="row"><label for="hl${u.id}">Jouw wachtwoord ter bevestiging</label><input id="hl${u.id}" name="huidig" type="password" autocomplete="current-password" required></div><button class="small secondary" type="submit">Herstellink maken</button><p class="fhint">Stuurt een mail met een link om een nieuw wachtwoord te kiezen, of toont de link als er geen mailserver is.</p></form>` : ''}
${n && !self ? `<form method="post" action="/admin/gebruikers/${u.id}/uitloggen" data-confirm="Alle sessies van ${esc(u.naam)} beëindigen?">${csrf}<button class="small secondary" type="submit">Overal uitloggen (${n})</button></form>` : ''}</div></div></details></article>`;
	};
	const open = flash && !flash.ok;
	return shell({ ...ctx, flash }, { title: 'Gebruikers', active: 'gebruikers', body: `<div class="page-head"><div><h1>Gebruikers</h1><p class="hint">${list.length} account${list.length === 1 ? '' : 's'}. Wie mag wat staat hieronder.</p></div></div>${legend}
${link ? `<section class="card"><h2>Link om door te geven</h2><p class="hint">Eenmalig en tijdelijk. Stuur hem alleen aan de persoon zelf, bij voorkeur niet per gewone e-mail of chat die anderen kunnen lezen.</p><p><input type="text" readonly value="${esc(link)}" aria-label="Link" onclick="this.select()"></p></section>` : ''}<div class="ulist">${list.map(card).join('')}</div>
<details class="card fold adduser"${open ? ' open' : ''}><summary>${icon('plus')} Gebruiker toevoegen</summary><form method="post" action="/admin/gebruikers">${csrf}<div class="two"><div class="row"><label for="ue">E-mailadres</label><input id="ue" name="email" type="email" required></div><div class="row"><label for="un">Naam</label><input id="un" name="naam" required maxlength="80"></div></div>
<div class="row"><label for="ur">Rol</label>${roleSel('editor', 'ur')}</div><div class="row"><label for="up">Startwachtwoord (optioneel)</label><input id="up" name="wachtwoord" type="password" minlength="12" autocomplete="new-password"><p class="fhint">Laat leeg om de persoon per e-mail uit te nodigen: die kiest dan zelf een wachtwoord via een link (drie dagen geldig). Vul je wel iets in (minstens 12 tekens), dan geef je dat wachtwoord zelf door.</p></div><div class="row"><label for="uh">Jouw wachtwoord ter bevestiging</label><input id="uh" name="huidig" type="password" autocomplete="current-password" required></div><button type="submit">Toevoegen</button></form></details>` });
}
function auditPage(ctx, { rows, total, page, filter, people }) {
	const pages = Math.max(1, Math.ceil(total / 100));
	const q = (extra = {}) => new URLSearchParams(Object.entries({ ...filter, ...extra }).filter(([, v]) => v)).toString();
	const f = filter;
	return shell(ctx, { title: 'Auditlog', active: 'audit', body: `<div class="page-head"><div><h1>Auditlog</h1><p class="hint">Elke wijziging, publicatie, override en inlogpoging. De tabel is append-only: de applicatie kan niets wijzigen of wissen (rijen ouder dan 180 dagen gaan maandelijks naar een gezipt archief).</p></div><a class="btn-link secondary small" href="/admin/audit.csv?${esc(q())}">${icon('send')} Exporteren (CSV)</a></div>
<form method="get" action="/admin/audit" class="toolbar"><label class="fl">Wie<select name="gebruiker"><option value="">iedereen</option><option value="systeem"${f.gebruiker === 'systeem' ? ' selected' : ''}>systeem</option>${people.map((u) => `<option value="${u.id}"${f.gebruiker === String(u.id) ? ' selected' : ''}>${esc(u.naam)}</option>`).join('')}</select></label>
<label class="fl">Actie bevat<input name="actie" value="${esc(f.actie)}" placeholder="bijv. publiceer"></label><label class="fl">Onderdeel bevat<input name="entiteit" value="${esc(f.entiteit)}" placeholder="bijv. pagina:3"></label>
<label class="fl">Van<input type="date" name="van" value="${esc(f.van)}"></label><label class="fl">Tot<input type="date" name="tot" value="${esc(f.tot)}"></label><button class="small" type="submit">Filteren</button>${Object.values(f).some(Boolean) ? '<a class="clear" href="/admin/audit">Wissen</a>' : ''}</form>
<p class="hint">${nf(total)} regel${total === 1 ? '' : 's'}.</p>
<section class="card flush"><div class="scroll"><table data-sortable><thead><tr><th>Tijd</th><th>Wie</th><th>Actie</th><th>Onderdeel</th><th>Details</th><th>Reden</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${esc(when(r.timestamp))}</td><td>${esc(r.naam || r.gebruiker || 'systeem')}</td><td>${esc(r.actie)}</td><td><code>${esc(r.entiteit)}</code></td><td class="detail">${esc(String(r.nieuwe_waarde || r.oude_waarde || '').slice(0, 160))}</td><td>${esc(r.override_reden || '')}</td></tr>`).join('')}</tbody></table></div>
${pages > 1 ? `<nav class="tabs" aria-label="Paginering">${Array.from({ length: Math.min(pages, 30) }, (_, i) => i + 1).map((n) => `<a href="/admin/audit?${q({ page: n })}"${n === page ? ' aria-current="page"' : ''}>${n}</a>`).join('')}</nav>` : ''}</section>` });
}
const ACTION_NL = { 'login.gelukt': 'Ingelogd', 'login.code_mislukt': 'Foute 2FA-code', logout: 'Uitgelogd', 'gebruiker.wachtwoord': 'Wachtwoord gewijzigd', 'gebruiker.gewijzigd': 'Account gewijzigd', 'gebruiker.uitgelogd': 'Andere apparaten uitgelogd', 'tekst.gepubliceerd': 'Tekst gepubliceerd', 'pagina.gepubliceerd': 'Pagina gepubliceerd', 'media.gewijzigd': 'Foto gewijzigd', 'media.verwijderd': 'Foto verwijderd', 'bericht.status': 'Status van bericht gewijzigd', 'bericht.verwijderd': 'Bericht verwijderd', 'media.geupload': 'Foto geüpload', 'media.plek': 'Foto op de site gewijzigd', 'pagina.aangemaakt': 'Pagina aangemaakt', 'pagina.verwijderd': 'Pagina verwijderd', 'bericht.toegewezen': 'Bericht toegewezen', 'bericht.notitie': 'Notitie bij bericht' };
function accountPage(ctx, { flash, tf = {}, sessions = [], activity = [], passkeys = [] }) {
	const me = ctx.session.user;
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	let two;
	if (tf.codes) two = `<section class="card"><h2>Herstelcodes</h2><p class="hint">Tweestapsverificatie staat aan. Bewaar deze codes veilig (wachtwoordmanager of geprint). Elke code werkt één keer als je je telefoon kwijt bent. Ze worden alleen nu getoond.</p><ul class="codes">${tf.codes.map((c) => `<li><code>${esc(c)}</code></li>`).join('')}</ul></section>`;
	else if (tf.setup) two = `<section class="card"><h2>Tweestapsverificatie instellen</h2><ol class="steps-list"><li>Open een authenticator-app op je telefoon en kies om een account toe te voegen.</li><li>Scan deze QR-code.<div class="qr-wrap">${qrSvg(tf.setup.uri, 'QR-code om het Aethra-account toe te voegen aan een authenticator-app')}</div><details class="alt"><summary>Scannen lukt niet?</summary><p>Kies “sleutel invoeren” (tijdgebonden) en typ: <code class="key">${esc(tf.setup.secret.replace(/(.{4})/g, '$1 ').trim())}</code></p></details></li><li>Vul de 6-cijferige code uit de app in.</li></ol>
<form method="post" action="/admin/2fa/confirm" class="inline">${csrf}<div class="row"><label for="c2">Code uit de app</label><input id="c2" name="code" inputmode="numeric" autocomplete="one-time-code" required></div><button type="submit">Bevestigen</button></form>
<form method="post" action="/admin/2fa/restart">${csrf}<button type="submit" class="secondary small">Nieuwe QR-code</button></form></section>`;
	else if (tf.enabled) two = `<section class="card"><div class="card-title"><h2>Tweestapsverificatie</h2><span class="pill ok">Aan</span></div><p class="hint">Je hebt nog ${tf.left} herstelcode${tf.left === 1 ? '' : 's'}. Uitzetten of nieuwe herstelcodes vragen je wachtwoord en een code uit de app.</p>
<form method="post" action="/admin/2fa/disable">${csrf}<div class="two"><div class="row"><label for="dp">Huidig wachtwoord</label><input id="dp" name="current" type="password" autocomplete="current-password" required></div><div class="row"><label for="dc">Code uit de app</label><input id="dc" name="code" autocomplete="one-time-code" required></div></div><div class="actions"><button type="submit" class="danger">Uitzetten</button> <button type="submit" formaction="/admin/2fa/recovery" class="secondary">Nieuwe herstelcodes</button></div></form></section>`;
	else two = `<section class="card"><div class="card-title"><h2>Tweestapsverificatie</h2><span class="pill st-warn">Uit</span></div><p class="hint">Sterk aanbevolen: een gestolen wachtwoord geeft dan geen toegang meer.</p><form method="post" action="/admin/2fa/start">${csrf}<div class="row"><label for="sp">Bevestig met je huidige wachtwoord</label><input id="sp" name="current" type="password" autocomplete="current-password" required></div><button type="submit">Instellen</button></form></section>`;
	const sess = `<section class="card"><h2>Ingelogd op</h2><ul class="plain sess">${sessions.map((s) => `<li>${icon('monitor')}<span class="sess-main"><strong>${esc(s.apparaat)}${s.huidig ? ' (dit apparaat)' : ''}</strong><span class="meta">Netwerk ${esc(s.netwerk)} · ingelogd ${esc(relTime(s.aangemaakt))} · laatst actief ${esc(relTime(s.laatst_gezien))}</span></span>${s.huidig ? '' : `<form method="post" action="/admin/account/sessies/${esc(s.hash)}/beeindigen" class="inline" data-confirm="Dit apparaat uitloggen?">${csrf}<button type="submit" class="small secondary">Uitloggen</button></form>`}</li>`).join('')}</ul>
${sessions.length > 1 ? `<form method="post" action="/admin/account/sessies-uit" data-confirm="Alle andere apparaten uitloggen?">${csrf}<button type="submit" class="secondary small">Alle andere apparaten uitloggen</button></form>` : '<p class="hint">Je bent alleen hier ingelogd.</p>'}</section>`;
	const pk = `<section class="card"><div class="card-title"><h2>Passkeys en beveiligingssleutels</h2><span class="pill ${passkeys.length ? 'ok' : 'st-standaard'}">${passkeys.length ? `${passkeys.length} ingesteld` : 'Geen'}</span></div><p class="hint">Inloggen met je vingerafdruk, gezicht, telefoon of een USB-sleutel in plaats van een code. Niet te phishen: de sleutel werkt alleen op dit adres. Je blijft eerst je wachtwoord invullen; de sleutel is de tweede stap.</p>
${passkeys.length ? `<ul class="plain sess">${passkeys.map((k) => `<li>${icon('lock')}<span class="sess-main"><strong>${esc(k.naam)}</strong><span class="meta">Toegevoegd ${esc(relTime(k.aangemaakt))}${k.laatst_gebruikt ? ` · laatst gebruikt ${esc(relTime(k.laatst_gebruikt))}` : ' · nog niet gebruikt'}</span></span><form method="post" action="/admin/passkeys/${k.id}/verwijderen" class="inline" data-confirm="Deze sleutel verwijderen?">${csrf}<input type="password" name="huidig" placeholder="jouw wachtwoord" autocomplete="current-password" aria-label="Jouw wachtwoord ter bevestiging" required><button type="submit" class="small danger">Verwijderen</button></form></li>`).join('')}</ul>` : ''}
<form data-passkey-add class="pk-add"><div class="two"><div class="row"><label for="pk-name">Naam (bijvoorbeeld “iPhone” of “YubiKey”)</label><input id="pk-name" name="naam" maxlength="60"></div><div class="row"><label for="pk-pw">Jouw wachtwoord ter bevestiging</label><input id="pk-pw" name="huidig" type="password" autocomplete="current-password" required></div></div><button type="submit" class="small">Passkey toevoegen</button><p class="err-text" id="pk-add-err" role="alert" hidden></p></form></section>`;
	const act = activity.length ? `<section class="card"><h2>Jouw recente activiteit</h2><ul class="plain act">${activity.map((a) => `<li><span>${esc(ACTION_NL[a.actie] || a.actie)}</span><time class="meta">${esc(relTime(a.timestamp))}</time></li>`).join('')}</ul></section>` : '';
	return shell({ ...ctx, flash }, { title: 'Mijn account', active: 'account', body: `<div class="page-head"><div class="who-head">${avatar(me.naam, 'lg')}<div><h1>${esc(me.naam)}</h1><p class="hint">${esc(me.email)} · ${esc(ROLE_INFO[me.rol][0])}: ${esc(ROLE_INFO[me.rol][1].toLowerCase())}</p></div></div></div>
<div class="acc-grid"><div>
<section class="card"><h2>Naam</h2><form method="post" action="/admin/account/naam" class="inline">${csrf}<label for="an" class="sr">Naam</label><input id="an" name="naam" value="${esc(me.naam)}" maxlength="80" required><button type="submit" class="small">Opslaan</button></form></section>
${me.rol !== 'lezer' ? `<form method="post" action="/admin/account/meldingen" class="card">${csrf}<h2>Meldingen</h2><label class="chk"><input type="checkbox" name="meld_nieuw_bericht" value="1"${me.meld_nieuw_bericht ? ' checked' : ''}> E-mail bij een nieuw bericht via de website</label><label class="chk"><input type="checkbox" name="meld_toewijzing" value="1"${me.meld_toewijzing ? ' checked' : ''}> E-mail als een bericht aan mij wordt toegewezen</label><label class="chk"><input type="checkbox" name="weekrapport" value="1"${me.weekrapport ? ' checked' : ''}> Weekrapport per e-mail (maandagochtend)</label><label class="chk"><input type="checkbox" name="meld_werkdagen" value="1"${me.meld_werkdagen ? ' checked' : ''}> Meldingen alleen op werkdagen (in het weekend wachten ze tot maandag 07:00)</label><p class="fhint">Mails komen binnen via de mailwachtrij. In de mail staat geen berichttekst, alleen een link naar het beheer.</p><div class="actions"><button type="submit" class="small">Opslaan</button><button type="button" class="secondary small" id="notifybtn" hidden>Meldingen in de browser aanzetten</button></div></form>` : ''}
<form method="post" action="/admin/account" class="card">${csrf}<h2>Wachtwoord wijzigen</h2><div class="row"><label for="cur">Huidig wachtwoord</label><input id="cur" name="current" type="password" autocomplete="current-password" required></div><div class="row"><label for="new">Nieuw wachtwoord</label><input id="new" name="password" type="password" autocomplete="new-password" minlength="12" required data-strength><div class="meter" id="meter" hidden><span></span></div><p class="fhint" id="meter-t">Minstens 12 tekens. Een zin van een paar woorden werkt het best.</p></div><div class="actions spread"><label class="chk"><input type="checkbox" data-showpw> Wachtwoorden tonen</label><button type="submit">Wijzigen</button></div></form>
${sess}</div><div>${two}${pk}${act}</div></div>`, scripts: ['/js/passkey.js'] });
}

function securityPage(ctx, d) {
	const card = (label, value, hint = '', cls = '') => `<div class="card mini ${cls}"><span class="meta">${esc(label)}</span><strong>${value}</strong>${hint ? `<span class="meta">${hint}</span>` : ''}</div>`;
	const rows = d.accounts.map((u) => `<tr${u.actief ? '' : ' class="muted"'}><td><strong>${esc(u.naam)}</strong><br><span class="meta">${esc(u.email)}</span></td><td>${esc(u.rol)}${u.actief ? '' : ' <span class="pill st-standaard">uitgeschakeld</span>'}</td><td>${u.tweestaps ? `<span class="pill st-ok">Ja</span> <span class="meta">${[u.totp ? 'app' : '', u.passkeys ? `${u.passkeys} passkey${u.passkeys === 1 ? '' : 's'}` : ''].filter(Boolean).join(' + ')}</span>` : '<span class="pill st-warn">Nee</span>'}</td><td>${u.laatste_login ? esc(when(u.laatste_login)) : '<span class="meta">nooit</span>'}</td><td>${u.sessies}</td><td>${u.flags.length ? u.flags.map((f) => `<span class="pill st-warn">${esc(f)}</span>`).join(' ') : '<span class="meta">Geen</span>'}</td></tr>`).join('');
	return shell(ctx, { title: 'Beveiliging', active: 'beveiliging', body: `<div class="page-head"><div><h1>Beveiliging</h1><p class="hint">Wie heeft toegang, hoe goed is dat beschermd, en staat het systeem veilig ingesteld? Dit overzicht verandert niets.</p></div><a class="button secondary" href="/admin/beveiligingsrapport.csv" download>Exporteren (CSV)</a></div>
<div class="rolecards sys">${card('Actieve accounts', String(d.actief))}${card('Zonder tweede stap', String(d.zonderTweestaps), d.zonderTweestaps ? 'Zet dit aan onder Instellingen of vraag ze het in te stellen.' : 'Iedereen heeft een tweede stap.', d.zonderTweestaps ? 'bad' : '')}${card('Met passkey', String(d.metPasskey))}${card('Aandachtspunten', String(d.aandacht), '', d.aandacht ? 'bad' : '')}</div>
<section class="card"><h2>Systeem</h2><ul class="plain">${d.checks.map((c) => `<li><span class="pill ${c.ok ? 'st-ok' : 'st-warn'}">${c.ok ? 'In orde' : 'Aandacht'}</span> <strong>${esc(c.titel)}</strong><br><span class="meta">${esc(c.uitleg)}</span></li>`).join('')}</ul></section>
<section class="card"><h2>Accounts</h2><div class="scroll"><table><thead><tr><th>Wie</th><th>Rol</th><th>Tweede stap</th><th>Laatste login</th><th>Sessies</th><th>Aandachtspunten</th></tr></thead><tbody>${rows}</tbody></table></div></section>` });
}


module.exports = { ROLE_INFO, usersPage, auditPage, ACTION_NL, accountPage, securityPage };
