'use strict';
/** Settings, system status, menu, SEO, link check, rules and redirects. */
const { LANGS, LANG_NAMES } = require('../../i18n');
const { esc, asset } = require('../../views');
const content = require('../content');
const { icon, nf, shell, table, when } = require('./common');

/* ---- redirects, users, audit, account, stats ---- */
function redirectsPage(ctx, list, { chains = [], page = 1, pages = 1, total = list.length } = {}) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const canWrite = ['beheerder', 'editor'].includes(ctx.session.user.rol);
	const hex = (t) => Buffer.from(String(t), 'utf8').toString('hex');
	const table = list.length ? `<form method="post" action="/admin/redirects/bulk" data-bulk>${csrf}${canWrite ? `<div class="bulkbar"><label class="selbox"><input type="checkbox" data-bulk-all aria-label="Alles selecteren"></label><span class="meta" data-bulk-count>Niets geselecteerd</span><button type="submit" class="small danger" data-bulk-go disabled data-confirm-msg="De geselecteerde redirects verwijderen?">Verwijderen</button></div>` : ''}<div class="scroll"><table data-sortable><thead><tr>${canWrite ? '<th></th>' : ''}<th>Van</th><th>Naar</th><th>Gebruikt</th></tr></thead><tbody>${list.map((r) => `<tr>${canWrite ? `<td><label class="selbox"><input type="checkbox" name="v_${hex(r.van)}" value="1" data-bulk-box aria-label="Selecteer ${esc(r.van)}"></label></td>` : ''}<td><code>${esc(r.van)}</code></td><td><code>${esc(r.naar)}</code></td><td>${r.hits}</td></tr>`).join('')}</tbody></table></div></form>` : '<p class="hint">Nog geen redirects. Ze ontstaan vanzelf als je het adres van een gepubliceerde pagina wijzigt.</p>';
	return shell(ctx, { title: 'Redirects', active: 'redirects', body: `<div class="page-head"><div><h1>Redirects <span class="count">(${nf(total)})</span></h1><p class="hint">Een oud adres stuurt bezoekers permanent (301) naar het nieuwe adres. Dat gebeurt automatisch als een adres van een gepubliceerde pagina verandert.</p></div><a class="btn-link secondary small" href="/admin/redirects.csv">${icon('send')} Exporteren (CSV)</a></div>
${chains.length ? `<section class="flash err">${icon('alert')}<span>${chains.length} redirect${chains.length === 1 ? '' : 's'} wijs${chains.length === 1 ? 't' : 'en'} naar een adres dat zelf weer doorverwijst. Bezoekers en zoekmachines hoppen dan twee keer.${canWrite ? ` <form method="post" action="/admin/redirects/inkorten" class="inline">${csrf}<button class="small" type="submit">Ketens inkorten</button></form>` : ''}</span></section>` : ''}
<section class="card flush">${table}${pagerNav((n) => `/admin/redirects?pagina=${n}`, page, pages)}</section>
${canWrite ? `<div class="mgrid2"><section class="card"><h2>Redirect toevoegen</h2><form method="post" action="/admin/redirects">${csrf}<div class="row"><label for="rv">Van (bijvoorbeeld /nl/oude-pagina)</label><input id="rv" name="van" required></div><div class="row"><label for="rn">Naar (bijvoorbeeld /nl/nieuwe-pagina)</label><input id="rn" name="naar" required></div><button type="submit">Toevoegen</button></form></section>
<section class="card"><h2>Veel tegelijk importeren</h2><p class="hint">Eén redirect per regel: <code>/nl/oud,/nl/nieuw</code>. Maximaal 500 regels. Een regel die niet kan, wordt overgeslagen en uitgelegd.</p><form method="post" action="/admin/redirects/importeren">${csrf}<div class="row"><label for="rf">Bestand kiezen (optioneel)</label><input id="rf" type="file" accept=".csv,.txt,text/csv,text/plain" data-fill="#rc"></div><div class="row"><label for="rc">Of plak hier</label><textarea id="rc" name="csv" rows="5" placeholder="/nl/oud,/nl/nieuw"></textarea></div><button type="submit">Importeren</button></form></section></div>` : ''}` });
}
/* ---- menu editor ---- */
function menuPage(ctx, data) {
	const canWrite = ['beheerder', 'editor'].includes(ctx.session.user.rol);
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const state = { menu: data.menu, fixed: data.fixed, pages: data.pages, langs: data.langs, names: LANG_NAMES, max: { header: 8, footer: 24 }, canWrite };
	const list = (id, title, hint, extra = '') => `<section class="card mnu" data-list="${id}"><div class="card-title"><h2>${title}</h2><span class="meta" data-count></span></div><p class="hint">${hint}</p>${extra}<ul class="mlist" data-items aria-label="${title}"></ul><p class="hint" data-empty hidden>Nog niets in dit menu.</p>${canWrite ? '<div class="addrow"><label class="sr" for="add-' + id + '">Toevoegen</label><select id="add-' + id + '" data-add-select></select><button type="button" class="secondary small" data-add>' + icon('plus') + ' Toevoegen</button></div>' : ''}</section>`;
	return shell({ ...ctx }, { title: 'Menu', active: 'menu', body: `<div class="page-head"><div><h1>Menu</h1><p class="hint">Bepaal welke links in het hoofdmenu en de voettekst staan, in welke volgorde en met welke tekst. Wijzigingen zijn pas zichtbaar na opslaan.</p></div>${data.custom ? '<span class="pill ok">Aangepast menu</span>' : '<span class="pill st-standaard">Standaardmenu</span>'}</div>
<div class="card mock"><div class="mock-bar"><strong>Zo ziet het eruit</strong><div class="chips" role="group" aria-label="Taal van het voorbeeld">${data.langs.map((l) => `<button type="button" class="chip" data-mlang="${l}" aria-pressed="${l === 'nl'}">${l.toUpperCase()}</button>`).join('')}</div></div>
<div class="mock-site"><span class="mock-brand">AETHRA</span><nav class="mock-nav" data-mock="header" aria-label="Voorbeeld hoofdmenu"></nav><span class="mock-btn" data-mock="cta"></span></div><div class="mock-foot"><span class="meta">Voettekst:</span><nav class="mock-nav" data-mock="footer" aria-label="Voorbeeld voettekst"></nav></div></div>
<form method="post" action="/admin/menu" id="menuform" data-state="${esc(JSON.stringify(state))}">${csrf}<input type="hidden" name="menu" id="menuinput">
<div class="mgrid2">${list('header', 'Hoofdmenu', 'Links bovenaan de site. Houd het kort: drie tot vijf links werkt het best.')}
<div>${list('footer', 'Voettekst', 'Links onderaan elke pagina.')}
<section class="card mnu" data-cta><div class="card-title"><h2>Knop rechtsboven</h2></div><p class="hint">Eén opvallende knop naast het hoofdmenu, bijvoorbeeld “Contact”.</p><div data-cta-box></div></section></div></div>
${canWrite ? `<div class="savebar" id="savebar"><span class="meta" id="menustate">Geen wijzigingen</span><button type="submit" id="menusave">Menu opslaan</button></div>` : '<p class="hint">Je hebt alleen leesrechten.</p>'}</form>
${canWrite && data.custom ? `<form method="post" action="/admin/menu/standaard" data-confirm="Terug naar het standaardmenu? Je aanpassingen gaan verloren." class="dz">${csrf}<button type="submit" class="secondary small">Terugzetten naar standaardmenu</button></form>` : ''}
<p class="hint">De rij met doelgroeppagina’s onderaan de voettekst en de taalkeuze staan vast.</p>` });
}

/* ---- settings and system ---- */
const fmtBytes = (b) => (b >= 1073741824 ? `${(b / 1073741824).toFixed(1).replace('.', ',')} GB` : b >= 1048576 ? `${(b / 1048576).toFixed(1).replace('.', ',')} MB` : `${Math.max(1, Math.round(b / 1024))} kB`);
function settingsPage(ctx, { values: v, mail, ip = '' }) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const langs = LANGS.map((l) => [l, LANG_NAMES[l]]);
	const texts = (prefix, label) => langs.map(([l, n]) => `<div class="row"><label for="${prefix}${l}">${label} (${esc(n)})</label><input id="${prefix}${l}" name="${prefix}${l}" maxlength="${prefix.startsWith('banner') ? 200 : 600}" lang="${l}" value="${esc(v[prefix + l] || '')}"></div>`).join('');
	return shell(ctx, { title: 'Instellingen', active: 'instellingen', body: `<div class="page-head"><div><h1>Instellingen</h1><p class="hint">Dingen die je niet in de code hoeft te wijzigen. Alleen voor beheerders; elke wijziging komt in het auditlog.</p></div></div>
<form method="post" action="/admin/instellingen" class="settings">${csrf}
<section class="card"><h2>Mededeling bovenaan de site</h2><p class="hint">Een smalle balk boven de header, bijvoorbeeld “We zijn op 12 november aanwezig op een beurs”. Houd het feitelijk: dezelfde redactionele regels gelden als voor de rest van de site.</p>
<label class="chk"><input type="checkbox" name="banner_aan" value="1"${v.banner_aan ? ' checked' : ''}> Mededeling tonen</label>
<div class="two"><div class="row"><label for="banner_tot">Tot en met (optioneel)</label><input id="banner_tot" type="date" name="banner_tot" value="${esc(v.banner_tot)}"><p class="fhint">Daarna verdwijnt de balk vanzelf.</p></div><div class="row"><label for="banner_link">Link (optioneel)</label><input id="banner_link" name="banner_link" maxlength="300" value="${esc(v.banner_link)}" placeholder="https://… of /adres"></div></div>
${texts('banner_tekst_', 'Tekst')}<p class="fhint">Laat een taal leeg om de Engelse tekst te gebruiken.</p></section>
<section class="card"><h2>Onderhoudsmodus</h2><p class="hint">Bezoekers zien een nette pagina (HTTP 503, zodat zoekmachines niet denken dat de site weg is). Het beheer blijft gewoon werken. Vergeet hem niet uit te zetten.</p>
<label class="chk"><input type="checkbox" name="onderhoud_aan" value="1"${v.onderhoud_aan ? ' checked' : ''}> Onderhoudsmodus aan</label>${texts('onderhoud_tekst_', 'Uitleg voor bezoekers')}</section>
<section class="card"><h2>Berichten</h2><div class="row"><label for="bewaar">Bewaartermijn van berichten (dagen)</label><input id="bewaar" type="number" name="bewaartermijn_dagen" min="30" max="1825" value="${esc(v.bewaartermijn_dagen)}"><p class="fhint">Daarna worden berichten automatisch verwijderd. Tussen 30 en 1825 dagen. Neem de termijn ook op in de privacyverklaring.</p></div></section>
<section class="card"><h2>Inloggen en toegang</h2>
<div class="row"><label for="mfa">Tweestapsverificatie verplicht voor</label><select id="mfa" name="tweestaps_verplicht">${[['niemand', 'Niemand (aanbevolen, maar niet verplicht)'], ['beheerder', 'Beheerders'], ['beheer_editor', 'Beheerders en editors'], ['iedereen', 'Iedereen met een account']].map(([k, t]) => `<option value="${k}"${v.tweestaps_verplicht === k ? ' selected' : ''}>${t}</option>`).join('')}</select><p class="fhint">Mensen krijgen 7 dagen om het in te stellen (een app of een passkey). Daarna komen ze pas verder in het beheer nadat ze het hebben gedaan.</p></div>
<div class="row"><label for="ipl">Beheer alleen bereikbaar vanaf deze netwerken (optioneel)</label><textarea id="ipl" name="beheer_ip_lijst" rows="3" placeholder="203.0.113.7&#10;192.168.1.0/24">${esc(v.beheer_ip_lijst)}</textarea><p class="fhint">Eén adres of bereik per regel. Leeg = overal bereikbaar (nog steeds met wachtwoord en eventueel tweede stap). Je huidige adres is <code>${esc(ip || 'onbekend')}</code> en moet in de lijst staan. Buitengesloten? Start de server met <code>ADMIN_IP_BYPASS=1</code> en pas de lijst aan. De site zelf blijft voor iedereen bereikbaar. Het filteren op land kan hier niet: daarvoor is een lijst met adresbereiken per land nodig.</p></div></section>
<section class="card"><h2>E-mail</h2><p>${mail.smtp ? '<span class="pill ok">Mailserver ingesteld</span>' : '<span class="pill st-warn">Geen mailserver</span>'} ${mail.team ? '<span class="pill ok">Teammelding aan</span>' : '<span class="pill st-standaard">Teammelding uit</span>'}</p>
<p class="hint">De mailserver staat om veiligheidsredenen niet in dit scherm maar in de omgeving van de server: <code>SMTP_HOST</code>, <code>SMTP_PORT</code>, <code>SMTP_USER</code>, <code>SMTP_PASS</code>, <code>MAIL_FROM</code> en optioneel <code>MAIL_TO</code>. Per persoon stel je meldingen in onder Mijn account.</p></section>
<div class="savebar"><button type="submit">Instellingen opslaan</button></div></form>` });
}
function systemPage(ctx, d) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const up = d.uptime >= 86400 ? `${Math.floor(d.uptime / 86400)} d ${Math.floor((d.uptime % 86400) / 3600)} u` : d.uptime >= 3600 ? `${Math.floor(d.uptime / 3600)} u ${Math.floor((d.uptime % 3600) / 60)} min` : `${Math.max(1, Math.floor(d.uptime / 60))} min`;
	const last = d.backups[0];
	const stale = !last || d.now - Date.parse(last.tijd) > 36 * 3600 * 1000;
	const card = (label, value, hint = '', cls = '') => `<div class="card mini ${cls}"><span class="meta">${esc(label)}</span><strong>${value}</strong>${hint ? `<span class="meta">${hint}</span>` : ''}</div>`;
	const failed = (d.queue.gefaald || 0) + (d.queue.mislukt || 0) + (d.outbox.gefaald || 0) + (d.outbox.mislukt || 0);
	return shell(ctx, { title: 'Systeem', active: 'systeem', body: `<div class="page-head"><div><h1>Systeem</h1><p class="hint">De gezondheid van de website en de database, en de back-ups.</p></div></div>
<div class="rolecards sys">${card('Database', d.dbOk ? 'In orde' : 'Niet bereikbaar', fmtBytes(d.dbBytes), d.dbOk ? '' : 'bad')}${card('Foto’s', `${nf(d.uploads.files)} bestanden`, fmtBytes(d.uploads.bytes))}${card('Schijfruimte', d.disk ? `${fmtBytes(d.disk.vrij)} vrij` : 'onbekend', d.disk ? `van ${fmtBytes(d.disk.totaal)}` : '')}${card('Laatste back-up', last ? esc(when(last.tijd)) : 'nog geen', stale ? 'Ouder dan 36 uur of nog geen: maak er een.' : `${d.backups.length} bewaard (maximaal ${d.keep})`, stale ? 'bad' : '')}
${card('Mailserver', d.smtp ? 'Ingesteld' : 'Niet ingesteld', failed ? `${failed} mail${failed === 1 ? '' : 's'} met problemen` : 'Geen problemen', d.smtp && !failed ? '' : 'bad')}${card('Versie', esc(d.versie), `Node ${esc(d.node)} · draait ${up}`)}${card('Cache', `${nf(d.cache.size)} pagina’s`, `${nf(d.cache.hits)} treffers, ${nf(d.cache.misses)} gemist`)}${card('Verbinding', d.secure ? 'Beveiligde cookies' : 'Cookies zonder Secure', d.siteUrl ? esc(d.siteUrl) : 'SITE_URL niet ingesteld', d.secure ? '' : 'bad')}</div>
${d.gezondheid.length ? `<section class="card"><h2>Aandachtspunten</h2><ul class="plain">${d.gezondheid.map((g) => `<li><span class="pill ${g.ernst === 'info' ? 'st-standaard' : 'st-warn'}">${esc(g.ernst)}</span> ${esc(g.bericht)}</li>`).join('')}</ul></section>` : ''}
<section class="card"><div class="card-title"><h2>Back-ups van de database</h2><form method="post" action="/admin/systeem/backup">${csrf}<button type="submit" class="small">Nu een back-up maken</button></form></div>
<p class="hint">Elke dag automatisch, de laatste ${d.keep} blijven bewaard in de map <code>data/backups</code>. Een back-up bevat alle gegevens, ook de versleutelde inloggegevens: bewaar gedownloade bestanden veilig. Foto’s staan in <code>data/uploads</code>; <code>npm run backup</code> kopieert alles.</p>
${d.backups.length ? `<div class="scroll"><table><thead><tr><th>Bestand</th><th>Gemaakt</th><th>Grootte</th><th>Downloaden</th></tr></thead><tbody>${d.backups.map((b) => `<tr><td><code>${esc(b.naam)}</code></td><td>${esc(when(b.tijd))}</td><td>${fmtBytes(b.grootte)}</td><td><form method="post" action="/admin/systeem/backup/${esc(b.naam)}" class="inline">${csrf}<input type="password" name="huidig" placeholder="jouw wachtwoord" autocomplete="current-password" aria-label="Jouw wachtwoord ter bevestiging" required><button class="small secondary" type="submit">Download</button></form></td></tr>`).join('')}</tbody></table></div>` : '<p class="hint">Nog geen back-ups.</p>'}
<details class="fold-lite"><summary>Hoe zet ik een back-up terug?</summary><ol class="steps-list"><li>Stop de website.</li><li>Voer uit in de projectmap: <code>node scripts/restore.js aethra-20260101-030000.db</code> (de naam uit de lijst, of een pad naar een gedownload bestand).</li><li>Het script controleert het bestand, zet de huidige database opzij als <code>aethra.db.before-restore-…</code> en plaatst de back-up.</li><li>Start de website weer.</li></ol></details></section>` });
}

/* ---- SEO, links, editorial rules ---- */
function seoPage(ctx, { rows, score, checkedAt, robots, sitemapUrls, siteUrl, env }) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const canWrite = ctx.session.user.rol !== 'lezer';
	const cls = { fout: 'st-warn', let_op: 'st-in_behandeling', info: 'st-standaard' };
	const sevOf = (r) => (r.findings.some((f) => f.ernst === 'fout') ? 'fout' : r.findings.some((f) => f.ernst === 'let_op') ? 'let_op' : 'goed');
	const table = `<div class="scroll"><table data-sortable><thead><tr><th>Pagina</th><th>Taal</th><th>Titel</th><th>Omschrijving</th><th>Bevindingen</th></tr></thead><tbody>${rows.map((r) => `<tr data-sev="${sevOf(r)}"><th scope="row"><a href="/${esc(r.lang)}${r.path === '/' ? '/' : esc(r.path)}" target="_blank" rel="noopener">${esc(r.label)}</a></th><td>${esc(r.lang.toUpperCase())}</td><td data-sort="${r.title.length}">${r.title.length}</td><td data-sort="${r.desc.length}">${r.desc.length}</td><td>${r.findings.length ? r.findings.map((f) => `<span class="pill ${cls[f.ernst]}" title="${esc(f.tekst)}">${esc(f.tekst)}</span>`).join(' ') : '<span class="pill ok">in orde</span>'}</td></tr>`).join('')}</tbody></table></div>`;
	return shell(ctx, { title: 'Zoekmachines', active: 'seo', body: `<div class="page-head"><div><h1>Zoekmachines</h1><p class="hint">Alle gepubliceerde pagina’s in alle talen, gecontroleerd zoals een bezoeker ze krijgt. Concepten staan er niet bij. ${checkedAt ? `Gecontroleerd om ${esc(new Date(checkedAt).toLocaleTimeString('nl-NL', { hour: '2-digit', minute: '2-digit' }))}; na elke publicatie wordt het vanzelf opnieuw berekend. <a href="/admin/seo?vernieuw=1">Nu opnieuw controleren</a>.` : ''}</p></div>${canWrite ? `<form method="post" action="/admin/seo/vernieuwen">${csrf}<button class="secondary small" type="submit">Sitemap vernieuwen</button></form>` : ''}</div>
<div class="rolecards"><div class="card mini"><span class="meta">Pagina’s</span><strong>${score.pages}</strong></div><div class="card mini ${score.bad ? 'bad' : ''}"><span class="meta">Met aandachtspunten</span><strong>${score.bad}</strong></div><div class="card mini"><span class="meta">In de sitemap</span><strong>${sitemapUrls} adressen</strong></div><div class="card mini ${env.siteUrl ? '' : 'bad'}"><span class="meta">Site-adres</span><strong>${env.siteUrl ? esc(siteUrl) : 'niet ingesteld'}</strong>${env.siteUrl ? '' : '<span class="meta">Zet SITE_URL, anders staan er geen echte adressen in de sitemap.</span>'}</div></div>
<div class="chips" role="group" aria-label="Filter"><button type="button" class="chip" data-sev-filter="all" aria-pressed="true">Alles <span class="n">${rows.length}</span></button><button type="button" class="chip" data-sev-filter="fout" aria-pressed="false">Fouten <span class="n">${rows.filter((r) => sevOf(r) === 'fout').length}</span></button><button type="button" class="chip" data-sev-filter="let_op" aria-pressed="false">Let op <span class="n">${rows.filter((r) => sevOf(r) === 'let_op').length}</span></button><button type="button" class="chip" data-sev-filter="goed" aria-pressed="false">In orde <span class="n">${rows.filter((r) => sevOf(r) === 'goed').length}</span></button></div>
<section class="card flush">${table}</section>
<section class="card"><h2>robots.txt</h2><p class="hint">Wat zoekmachines en AI-bots mogen. Zoek- en antwoordbots mogen alles behalve het beheer. Bots die alleen trainen zijn ${env.training ? 'toegestaan (AI_TRAINING=allow)' : 'geblokkeerd'}; dat is een licentiekeuze en raakt vindbaarheid niet. Je past dit aan in de omgeving van de server.</p><pre class="code">${esc(robots)}</pre></section>
<section class="card"><h2>Sitemap en meldingen</h2><p class="hint">De sitemap staat op <a href="/sitemap.xml" target="_blank" rel="noopener">/sitemap.xml</a> met de talen als alternatief per pagina, en wordt bij elke publicatie vanzelf bijgewerkt. ${env.indexNow ? 'IndexNow staat aan: nieuwe adressen kun je direct melden met <code>npm run indexnow</code>.' : 'IndexNow staat uit (INDEXNOW_KEY niet ingesteld).'}</p></section>` });
}
const pagerNav = (href, page, pages) => (pages > 1 ? `<nav class="tabs" aria-label="Paginering">${Array.from({ length: Math.min(pages, 40) }, (_, i) => i + 1).map((n) => `<a href="${href(n)}"${n === page ? ' aria-current="page"' : ''}>${n}</a>`).join('')}</nav>` : '');
function linksPage(ctx, { results, last, running, canRun, page = 1, pages = 1 }) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const failedNow = (r) => (r.status === null ? !!r.fout && r.fout !== 'niet gecontroleerd' : r.status >= 400);
	const bad = failedNow;
	const broken = results.filter((r) => failedNow(r) && (r.soort === 'intern' || (r.reeks || 0) >= 2));
	const doubtful = results.filter((r) => failedNow(r) && r.soort === 'extern' && (r.reeks || 0) < 2);
	const total = results.length;
	const shown = results.slice((page - 1) * 100, page * 100);
	const rows = (list) => `<div class="scroll"><table data-sortable><thead><tr><th>Link</th><th>Staat op</th><th>Soort</th><th>Uitkomst</th></tr></thead><tbody>${list.map((r) => `<tr><td><code>${esc(r.url.length > 70 ? r.url.slice(0, 70) + '…' : r.url)}</code></td><td>${esc(r.bron)}</td><td>${esc(r.soort)}</td><td><span class="pill ${bad(r) ? 'st-warn' : r.status >= 300 ? 'st-in_behandeling' : 'ok'}">${r.status == null ? esc(r.fout || 'onbekend') : `${r.status}${r.fout ? ' · ' + esc(r.fout) : ''}`}</span></td></tr>`).join('')}</tbody></table></div>`;
	return shell(ctx, { title: 'Linkcontrole', active: 'links', body: `${running ? '<meta http-equiv="refresh" content="6">' : ''}<div class="page-head"><div><h1>Linkcontrole</h1><p class="hint">Controleert alle links op de gepubliceerde pagina’s: interne links tegen de site zelf, externe links met een verzoek aan de andere kant. Eens per week automatisch. ${last ? `Laatste controle: ${esc(when(last))}.` : 'Er is nog geen controle geweest.'}</p></div>${canRun ? `<form method="post" action="/admin/links/controleren">${csrf}<button type="submit" class="small"${running ? ' disabled' : ''}>${running ? 'Bezig…' : 'Nu controleren'}</button></form>` : ''}</div>
${running ? '<p class="flash" role="status">' + icon('info') + '<span>De controle loopt. Deze pagina ververst vanzelf.</span></p>' : ''}
<section class="card flush"><h2 class="pad">Kapotte links (${broken.length})</h2>${broken.length ? rows(broken) : `<p class="hint pad">${last ? 'Geen kapotte links gevonden.' : 'Nog niets gecontroleerd.'}</p>`}</section>
${doubtful.length ? `<section class="card flush"><h2 class="pad">Even afwachten (${doubtful.length})</h2><p class="hint pad">Deze externe links reageerden één keer niet. Een link telt pas als kapot als hij bij twee controles met minstens een dag ertussen faalt: sites hebben soms een slechte dag.</p>${rows(doubtful)}</section>` : ''}
<details class="card fold"${page > 1 ? ' open' : ''}><summary>Alle gecontroleerde links (${total})</summary>${shown.length ? rows(shown) + pagerNav((n) => `/admin/links?pagina=${n}`, page, pages) : '<p class="hint">Nog niets gecontroleerd.</p>'}</details>` });
}
function rulesPage(ctx, { builtin, extra }) {
	const csrf = `<input type="hidden" name="csrf" value="${esc(ctx.session.csrf)}">`;
	const chips = (list) => `<div class="tags">${list.map((t) => `<span class="pill st-standaard">${esc(t)}</span>`).join('')}</div>`;
	const mine = (soort) => extra.filter((r) => r.soort === soort);
	const list = (soort) => (mine(soort).length ? `<ul class="plain">${mine(soort).map((r) => `<li class="rule"><span><strong>${esc(r.term)}</strong>${r.toelichting ? `<span class="meta"> · ${esc(r.toelichting)}</span>` : ''}</span><form method="post" action="/admin/regels/${r.id}/verwijderen" class="inline" data-confirm="Deze term verwijderen?">${csrf}<button class="small danger" type="submit">Verwijderen</button></form></li>`).join('')}</ul>` : '<p class="hint">Nog geen eigen termen.</p>');
	return shell(ctx, { title: 'Redactionele regels', active: 'regels', body: `<div class="page-head"><div><h1>Redactionele regels</h1><p class="hint">De controle die elke publicatie doorloopt. De vaste regels hieronder zitten in de software en kun je niet versoepelen. Je kunt wel eigen termen toevoegen. Het gaat om juridische en inhoudelijke grenzen: overleg met het team voordat je iets wijzigt.</p></div></div>
<section class="card"><h2>Vaste regels</h2><h3>Niet toegestaan (blokkeert publiceren)</h3>${chips(builtin.verboden)}<p class="hint">Een zin die zegt dat iets <em>niet</em> wordt aangeboden (“geen aanbod van aandelen”) mag wel: dat is de disclaimer zelf.</p><h3>Waarschuwing (publiceren kan met een reden)</h3>${chips(builtin.waarschuwing)}<h3>Technisch detail (waarschuwing: het “hoe” bespreken we in een gesprek)</h3>${chips(builtin.technisch)}<p class="hint">Verder altijd: een getal heeft een bron nodig, investeerdersmateriaal vermeldt dat het geen aanbod is, en een publicatie zonder omschrijving voor zoekresultaten geeft een waarschuwing.</p></section>
<div class="mgrid2"><section class="card"><h2>Eigen termen: niet toegestaan</h2>${list('verboden')}</section><section class="card"><h2>Eigen termen: waarschuwing</h2>${list('waarschuwing')}</section></div>
<section class="card"><h2>Term toevoegen</h2><form method="post" action="/admin/regels">${csrf}<div class="two"><div class="row"><label for="rt">Woord of zin</label><input id="rt" name="term" maxlength="60" required></div><div class="row"><label for="rs">Wat moet er gebeuren?</label><select id="rs" name="soort"><option value="waarschuwing">Waarschuwing (publiceren kan met een reden)</option><option value="verboden">Niet toegestaan (blokkeert publiceren)</option></select></div></div><div class="row"><label for="rn">Toelichting (optioneel, voor het team)</label><input id="rn" name="toelichting" maxlength="200"></div><p class="fhint">Hoofdletters maken niet uit en de term geldt alleen als los woord. Een nieuwe term geldt direct, in alle talen, bij elke publicatie en planning.</p><button type="submit">Toevoegen</button></form></section>` });
}


module.exports = { redirectsPage, menuPage, fmtBytes, settingsPage, systemPage, seoPage, pagerNav, linksPage, rulesPage };
